# -*- coding: utf-8 -*-
"""emoticons.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lchC8OhU_cDhdhp8FZSolh_ecQa0edmh
"""

EMOTICONS_EMO = {
    u")))":"cười to", # lỗi chính tả
    u"))":"cười", # lỗi chính tả
    u":)))":"cười to",
    u":)":"cười",
    u":]]]":"cười to",
    u":]":"cười",
    u"=]]]":"cười to",
    u"=]":"cười",
    u"=)))":"cười to",
    u"=)":"cười",
    u":D":"cười",
    u"XD":"cười to",
    u":3":"cười",
    u":>":"cười",
    u":(":"buồn",
    u":((":"rất buồn",
    u":<":"buồn",
    u">_<":"nhăn mặt",
    u"><":"nhăn mặt",
    u"-_-":"chán",
    u"=_=":"chán",
    u"==":"chán",
    u"._.":"bối rối",
    u"-.-":"bối rối",
    u"@@":"bối rối",
    u"^_^":"vui",
    u"^_^":"vui",
    u"^O^":"vui",
    u"^o^":"vui",
    u"T_T":"khóc",
    u"ToT":"khóc",
    u";_;":"khóc",
    u";-;":"khóc",
    u"T.T":"khóc",
    u"TT":"khóc",
    u"^^":"cười",
    u"^—^":"cười",
    u":O":"bất ngờ",
    u"o.O":"bất ngờ",
    u"o.o":"bất ngờ",
    u"oO":"bất ngờ",
    u"<3":"yêu thích"
}